// <auto-generated />
namespace Eicm.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class movevendor_accountintovendorschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movevendor_accountintovendorschema));
        
        string IMigrationMetadata.Id
        {
            get { return "201708221404287_move vendor_account into vendor schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
