// <auto-generated />
namespace Eicm.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatecontracttablenullablefields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecontracttablenullablefields));
        
        string IMigrationMetadata.Id
        {
            get { return "201709181828081_update-contract-table-nullable-fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
